<a href="https://colab.research.google.com/github/Ajblahblah-01/ML-Models/blob/main/house_price_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import userdata
key = userdata.get('KAGGLE_API_TOKEN')

import os
# set the env variable KAGGLE_API_TOKEN
os.environ['KAGGLE_API_TOKEN'] = key

In [47]:
!kaggle competitions download -c house-prices-advanced-regression-techniques

# unzip house-prices-advanced-regression-techniques.zip and keep them in data folder
!unzip -qq house-prices-advanced-regression-techniques.zip -d data

Downloading house-prices-advanced-regression-techniques.zip to /content
100% 199k/199k [00:00<00:00, 404kB/s]

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [129]:
df = pd.read_csv('data/train.csv')
print(f'shape of df {df.shape}\n')
df.head()

shape of df (1460, 81)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [130]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [132]:
def fillNone(keyArr):
  for key in keyArr:
    df[key] = df[key].fillna('None')

def fillMean(keyArr):
  for key in keyArr:
    df[key] = df[key].fillna(df[key].mean())

def fillZero(keyArr):
  for key in keyArr:
    df[key] = df[key].fillna(0)

def fillMode(keyArr):
  for key in keyArr:
    df[key] = df[key].fillna(df[key].mode()[0])

def handleMissingValues():
  df.drop(['Alley', 'PoolQC', 'MiscFeature'], axis=1, inplace=True)
  fillNone(['FireplaceQu', 'MasVnrType', 'Fence', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
            'BsmtFinType2', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond'])
  fillMean(['LotFrontage', 'MasVnrArea'])
  fillZero(['GarageYrBlt'])
  fillMode(['Electrical'])

In [133]:
handleMissingValues()

# Display the count of missing values for all columns
print("\nMissing values count after imputation:")
print(df.isnull().sum()[df.isnull().sum() > 0])

Missing values count after imputation:
Series([], dtype: int64)

In [134]:
df.shape

(1460, 78)

In [135]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 78 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   LotShape       1460 non-null   object
 7   LandContour    1460 non-null   object
 8   Utilities      1460 non-null   object
 9   LotConfig      1460 non-null   object
 10  LandSlope      1460 non-null   object
 11  Neighborhood   1460 non-null   object
 12  Condition1     1460 non-null   object
 13  Condition2     1460 non-null   object
 14  BldgType       1460 non-null   object
 15  HouseStyle     1460 non-null   object
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   object
 21  RoofMatl       1460 non-null   object
 22  Exterior1st    1460 non-null   object
 23  Exterior2nd    1460 non-null   object
 24  MasVnrType     1460 non-null   object
 25  MasVnrArea     1460 non-null   float64
 26  ExterQual      1460 non-null   object
 27  ExterCond      1460 non-null   object
 28  Foundation     1460 non-null   object
 29  BsmtQual       1460 non-null   object
 30  BsmtCond       1460 non-null   object
 31  BsmtExposure   1460 non-null   object
 32  BsmtFinType1   1460 non-null   object
 33  BsmtFinSF1     1460 non-null   int64
 34  BsmtFinType2   1460 non-null   object
 35  BsmtFinSF2     1460 non-null   int64
 36  BsmtUnfSF      1460 non-null   int64
 37  TotalBsmtSF    1460 non-null   int64
 38  Heating        1460 non-null   object
 39  HeatingQC      1460 non-null   object
 40  CentralAir     1460 non-null   object
 41  Electrical     1460 non-null   object
 42  1stFlrSF       1460 non-null   int64
 43  2ndFlrSF       1460 non-null   int64
 44  LowQualFinSF   1460 non-null   int64
 45  GrLivArea      1460 non-null   int64
 46  BsmtFullBath   1460 non-null   int64
 47  BsmtHalfBath   1460 non-null   int64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchenAbvGr   1460 non-null   int64
 52  KitchenQual    1460 non-null   object
 53  TotRmsAbvGrd   1460 non-null   int64
 54  Functional     1460 non-null   object
 55  Fireplaces     1460 non-null   int64
 56  FireplaceQu    1460 non-null   object
 57  GarageType     1460 non-null   object
 58  GarageYrBlt    1460 non-null   float64
 59  GarageFinish   1460 non-null   object
 60  GarageCars     1460 non-null   int64
 61  GarageArea     1460 non-null   int64
 62  GarageQual     1460 non-null   object
 63  GarageCond     1460 non-null   object
 64  PavedDrive     1460 non-null   object
 65  WoodDeckSF     1460 non-null   int64
 66  OpenPorchSF    1460 non-null   int64
 67  EnclosedPorch  1460 non-null   int64
 68  3SsnPorch      1460 non-null   int64
 69  ScreenPorch    1460 non-null   int64
 70  PoolArea       1460 non-null   int64
 71  Fence          1460 non-null   object
 72  MiscVal        1460 non-null   int64
 73  MoSold         1460 non-null   int64
 74  YrSold         1460 non-null   int64
 75  SaleType       1460 non-null   object
 76  SaleCondition  1460 non-null   object
 77  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(40)
memory usage: 889.8+ KB

In [136]:
categorical_features = df.select_dtypes(include='object').columns.tolist()
print(f"Identified categorical features: {categorical_features}")

Identified categorical features: ['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'Fence', 'SaleType', 'SaleCondition']

In [137]:
# one hot encoding: MSZoning, Street, LandContour, LotConfig, Neighborhood, Condition1, Condition2 (check if we can combine the 2), BldgType, HouseStyle, RoofStyle, RoofMatl, Exterior1st, Exterior2nd(check for combine for 1 & 2), MasVnrType, Foundation, Heating, Electrical, GarageType, SaleType


# Ordinal Encoding: LotShape, Utilities, LandSlope, ExterQual, ExterCond, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinType2 (check for combine), HeatingQC, CentralAir, KitchenQual, Functional, FireplaceQu, GarageFinish, GarageQual, GarageCond, PavedDrive, Fence, SaleCondition

In [138]:
def hanldeOneHotEncoding():
  # 1. Combine Condition1 and Condition2
  conditions = pd.unique(df[['Condition1', 'Condition2']].values.ravel())
  for cond in conditions:
      if cond != 'Norm': # Use Norm as the baseline
          df[f'Condition_{cond}'] = ((df['Condition1'] == cond) | (df['Condition2'] == cond)).astype(int)

  # 2. Combine Exterior1st and Exterior2nd
  exteriors = pd.unique(df[['Exterior1st', 'Exterior2nd']].values.ravel())
  for ext in exteriors:
      if pd.notna(ext):
          df[f'Exterior_{ext}'] = ((df['Exterior1st'] == ext) | (df['Exterior2nd'] == ext)).astype(int)

  # List of other columns for standard one-hot encoding
  oh_cols = [
      'MSZoning', 'Street', 'LandContour', 'LotConfig', 'Neighborhood',
      'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'MasVnrType',
      'Foundation', 'Heating', 'Electrical', 'GarageType', 'SaleType', 'SaleCondition'
  ]

  # Apply get_dummies and explicitly convert booleans to integers
  df = pd.get_dummies(df, columns=oh_cols, drop_first=True, dtype=int)

  # Drop the original overlapping columns that were combined manually
  df.drop(['Condition1', 'Condition2', 'Exterior1st', 'Exterior2nd'], axis=1, inplace=True)

  print(f"New shape after one-hot encoding: {df.shape}")
  # Show all columns in the display
  with pd.option_context('display.max_columns', None):
      display(df.head())


def handleOrdinalEncoding():
  # Define ordinal mappings based on standard house pricing dataset conventions
  # Quality/Condition scales: Ex (Excellent), Gd (Good), TA (Typical), Fa (Fair), Po (Poor), None
  qual_map = {'Ex': 5, 'Gd': 4, 'TA': 3, 'Fa': 2, 'Po': 1, 'None': 0}

  # Mapping for BsmtExposure
  exposure_map = {'Gd': 4, 'Av': 3, 'Mn': 2, 'No': 1, 'None': 0}

  # Mapping for BsmtFinType
  fintype_map = {'GLQ': 6, 'ALQ': 5, 'BLQ': 4, 'Rec': 3, 'LwQ': 2, 'Unf': 1, 'None': 0}

  # Mapping for Functional
  func_map = {'Typ': 7, 'Min1': 6, 'Min2': 5, 'Mod': 4, 'Maj1': 3, 'Maj2': 2, 'Sev': 1, 'Sal': 0}

  # Mapping for GarageFinish
  garage_map = {'Fin': 3, 'RFn': 2, 'Unf': 1, 'None': 0}

  # Mapping for LotShape
  shape_map = {'Reg': 3, 'IR1': 2, 'IR2': 1, 'IR3': 0}

  # Mapping for LandSlope
  slope_map = {'Gtl': 2, 'Mod': 1, 'Sev': 0}

  # Mapping for Utilities
  util_map = {'AllPub': 3, 'NoSewr': 2, 'NoSeWa': 1, 'ELO': 0}

  # Apply transformations
  ordinal_cols = {
      'ExterQual': qual_map, 'ExterCond': qual_map, 'HeatingQC': qual_map,
      'KitchenQual': qual_map, 'FireplaceQu': qual_map, 'GarageQual': qual_map, 'GarageCond': qual_map,
      'BsmtQual': qual_map, 'BsmtCond': qual_map,
      'BsmtExposure': exposure_map,
      'BsmtFinType1': fintype_map, 'BsmtFinType2': fintype_map,
      'Functional': func_map,
      'GarageFinish': garage_map,
      'LotShape': shape_map,
      'LandSlope': slope_map,
      'Utilities': util_map,
      'CentralAir': {'Y': 1, 'N': 0},
      'PavedDrive': {'Y': 2, 'P': 1, 'N': 0}
  }

  for col, mapping in ordinal_cols.items():
      if col in df.columns:
          df[col] = df[col].map(mapping)

  # Check for Fence and SaleCondition separately as they are more categorical/nominal
  # but can be ranked roughly by desirability
  df['Fence'] = df['Fence'].map({'GdPrv': 4, 'MnPrv': 3, 'GdWo': 2, 'MnWw': 1, 'None': 0})

  display(df[list(ordinal_cols.keys()) + ['Fence']].head())


def handleEncoding():
  handleOrdinalEncoding()
  hanldeOneHotEncoding()

In [139]:
def hanldeOneHotEncoding():
  global df
  # 1. Combine Condition1 and Condition2
  conditions = pd.unique(df[['Condition1', 'Condition2']].values.ravel())
  for cond in conditions:
      if cond != 'Norm': # Use Norm as the baseline
          df[f'Condition_{cond}'] = ((df['Condition1'] == cond) | (df['Condition2'] == cond)).astype(int)

  # 2. Combine Exterior1st and Exterior2nd
  exteriors = pd.unique(df[['Exterior1st', 'Exterior2nd']].values.ravel())
  for ext in exteriors:
      if pd.notna(ext):
          df[f'Exterior_{ext}'] = ((df['Exterior1st'] == ext) | (df['Exterior2nd'] == ext)).astype(int)

  # List of other columns for standard one-hot encoding
  oh_cols = [
      'MSZoning', 'Street', 'LandContour', 'LotConfig', 'Neighborhood',
      'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'MasVnrType',
      'Foundation', 'Heating', 'Electrical', 'GarageType', 'SaleType',
      'SaleCondition'
  ]

  # Apply get_dummies and explicitly convert booleans to integers
  df = pd.get_dummies(df, columns=oh_cols, drop_first=True, dtype=int)

  # Drop the original overlapping columns that were combined manually
  df.drop(['Condition1', 'Condition2', 'Exterior1st', 'Exterior2nd'], axis=1, inplace=True)


def handleOrdinalEncoding():
  global df
  qual_map = {'Ex': 5, 'Gd': 4, 'TA': 3, 'Fa': 2, 'Po': 1, 'None': 0}
  exposure_map = {'Gd': 4, 'Av': 3, 'Mn': 2, 'No': 1, 'None': 0}
  fintype_map = {'GLQ': 6, 'ALQ': 5, 'BLQ': 4, 'Rec': 3, 'LwQ': 2, 'Unf': 1, 'None': 0}
  func_map = {'Typ': 7, 'Min1': 6, 'Min2': 5, 'Mod': 4, 'Maj1': 3, 'Maj2': 2, 'Sev': 1, 'Sal': 0}
  garage_map = {'Fin': 3, 'RFn': 2, 'Unf': 1, 'None': 0}
  shape_map = {'Reg': 3, 'IR1': 2, 'IR2': 1, 'IR3': 0}
  slope_map = {'Gtl': 2, 'Mod': 1, 'Sev': 0}
  util_map = {'AllPub': 3, 'NoSewr': 2, 'NoSeWa': 1, 'ELO': 0}

  ordinal_cols = {
      'ExterQual': qual_map, 'ExterCond': qual_map, 'HeatingQC': qual_map,
      'KitchenQual': qual_map, 'FireplaceQu': qual_map, 'GarageQual': qual_map, 'GarageCond': qual_map,
      'BsmtQual': qual_map, 'BsmtCond': qual_map,
      'BsmtExposure': exposure_map,
      'BsmtFinType1': fintype_map, 'BsmtFinType2': fintype_map,
      'Functional': func_map,
      'GarageFinish': garage_map,
      'LotShape': shape_map,
      'LandSlope': slope_map,
      'Utilities': util_map,
      'CentralAir': {'Y': 1, 'N': 0},
      'PavedDrive': {'Y': 2, 'P': 1, 'N': 0}
  }

  for col, mapping in ordinal_cols.items():
      if col in df.columns:
          df[col] = df[col].map(mapping)
  df['Fence'] = df['Fence'].map({'GdPrv': 4, 'MnPrv': 3, 'GdWo': 2, 'MnWw': 1, 'None': 0})

def checkIfAnyColumnsLeft():
  remaining = df.select_dtypes(include=['object', 'category']).columns.tolist()
  if remaining:
    print(f"Warning: The following categorical columns were NOT encoded: {remaining}")
  else:
    print("Success: No categorical columns remaining.")


def handleEncoding():
  handleOrdinalEncoding()
  hanldeOneHotEncoding()
  checkIfAnyColumnsLeft()
  print(f"New shape after encoding: {df.shape}")

In [140]:
handleEncoding()

Success: No categorical columns remaining.
New shape after encoding: (1460, 180)

In [141]:
# Future scope: convert this into a pipeline

In [142]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,LotShape,Utilities,LandSlope,OverallQual,OverallCond,YearBuilt,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
count,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,2.591781,2.998630,1.937671,6.099315,5.575342,1971.267808,...,0.003425,0.003425,0.083562,0.002055,0.867808,0.002740,0.008219,0.013699,0.820548,0.085616
std,421.610009,42.300571,22.024023,9981.264932,0.582296,0.052342,0.276232,1.382997,1.112799,30.202904,...,0.058440,0.058440,0.276824,0.045299,0.338815,0.052289,0.090317,0.116277,0.383862,0.279893
min,1.000000,20.000000,21.000000,1300.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1872.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,365.750000,20.000000,60.000000,7553.500000,2.000000,3.000000,2.000000,5.000000,5.000000,1954.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,730.500000,50.000000,70.049958,9478.500000,3.000000,3.000000,2.000000,6.000000,5.000000,1973.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,1095.250000,70.000000,79.000000,11601.500000,3.000000,3.000000,2.000000,7.000000,6.000000,2000.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000
max,1460.000000,190.000000,313.000000,215245.000000,3.000000,3.000000,2.000000,10.000000,9.000000,2010.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [143]:
from scipy.stats import skew

# Identify encoded columns from previous steps
encoded_cols = list(ordinal_cols.keys()) + ['Fence'] + [col for col in df.columns if '_' in col]

# Identify original numerical columns that were NOT encoded
# We exclude 'Id' as it is just an index
original_numeric = [col for col in df.columns if col not in encoded_cols and col != 'Id' and df[col].dtype != 'object']

# Calculate skewness
skewness_values = df[original_numeric].apply(lambda x: skew(x.dropna())).sort_values(ascending=False)

print('Skewness of non-encoded numerical columns:')
display(skewness_values)

# Flag high skewness
high_skew_non_encoded = skewness_values[abs(skewness_values) > 0.75]
print(f'\nFound {len(high_skew_non_encoded)} non-encoded columns with high skewness (>0.75):')
display(high_skew_non_encoded)

Skewness of non-encoded numerical columns:

MiscVal          24.451640
PoolArea         14.813135
LotArea          12.195142
3SsnPorch        10.293752
LowQualFinSF      9.002080
KitchenAbvGr      4.483784
BsmtFinSF2        4.250888
ScreenPorch       4.117977
BsmtHalfBath      4.099186
EnclosedPorch     3.086696
MasVnrArea        2.673661
LotFrontage       2.382499
OpenPorchSF       2.361912
SalePrice         1.880941
BsmtFinSF1        1.683771
WoodDeckSF        1.539792
TotalBsmtSF       1.522688
MSSubClass        1.406210
1stFlrSF          1.375342
GrLivArea         1.365156
BsmtUnfSF         0.919323
2ndFlrSF          0.812194
OverallCond       0.692355
TotRmsAbvGrd      0.675646
HalfBath          0.675203
Fireplaces        0.648898
BsmtFullBath      0.595454
OverallQual       0.216721
MoSold            0.211835
BedroomAbvGr      0.211572
GarageArea        0.179796
YrSold            0.096170
FullBath          0.036524
GarageCars       -0.342197
YearRemodAdd     -0.503044
YearBuilt        -0.612831
GarageYrBlt      -3.865524
dtype: float64

Found 23 non-encoded columns with high skewness (>0.75):

MiscVal          24.451640
PoolArea         14.813135
LotArea          12.195142
3SsnPorch        10.293752
LowQualFinSF      9.002080
KitchenAbvGr      4.483784
BsmtFinSF2        4.250888
ScreenPorch       4.117977
BsmtHalfBath      4.099186
EnclosedPorch     3.086696
MasVnrArea        2.673661
LotFrontage       2.382499
OpenPorchSF       2.361912
SalePrice         1.880941
BsmtFinSF1        1.683771
WoodDeckSF        1.539792
TotalBsmtSF       1.522688
MSSubClass        1.406210
1stFlrSF          1.375342
GrLivArea         1.365156
BsmtUnfSF         0.919323
2ndFlrSF          0.812194
GarageYrBlt      -3.865524
dtype: float64

In [144]:
# Apply log1p transformation to all skewed features (skew > 0.75)
skewed_features = high_skew_non_encoded.index
df[skewed_features] = np.log1p(df[skewed_features])

print(f"Applied log transformation to {len(skewed_features)} columns.")

# Recalculate skewness to verify improvement
skewness_after = df[skewed_features].apply(lambda x: skew(x)).sort_values(ascending=False)
print("\nSkewness after transformation (selected columns):")
display(skewness_after)

Applied log transformation to 23 columns.

Skewness after transformation (selected columns):

PoolArea         14.348342
3SsnPorch         7.727026
LowQualFinSF      7.452650
MiscVal           5.165390
BsmtHalfBath      3.929022
KitchenAbvGr      3.865437
ScreenPorch       3.147171
BsmtFinSF2        2.521100
EnclosedPorch     2.110104
MasVnrArea        0.480626
2ndFlrSF          0.289346
MSSubClass        0.248741
WoodDeckSF        0.153379
SalePrice         0.121222
1stFlrSF          0.080032
GrLivArea        -0.006134
OpenPorchSF      -0.023373
LotArea          -0.137263
BsmtFinSF1       -0.617774
LotFrontage      -0.891060
BsmtUnfSF        -2.184257
GarageYrBlt      -3.883418
TotalBsmtSF      -5.149373
dtype: float64

In [145]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import mean_squared_error
import numpy as np

X = df.drop(columns=["SalePrice"])
y = df["SalePrice"]  # already log-transformed

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Helper function to evaluate any model
def evaluate(name, model, X_train, y_train, X_val, y_val):
    model.fit(X_train, y_train)
    preds = model.predict(X_val)
    rmse = np.sqrt(mean_squared_error(y_val, preds))

    # Cross-val for more stable estimate
    cv_scores = cross_val_score(model, X_train, y_train,
                                cv=5, scoring="neg_root_mean_squared_error")
    cv_rmse = -cv_scores.mean()

    print(f"{name:30s} | Val RMSE: {rmse:.4f} | CV RMSE: {cv_rmse:.4f}")
    return model, rmse

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Columns: 180 entries, Id to SaleCondition_Partial
dtypes: float64(23), int64(157)
memory usage: 2.0 MB

In [147]:
from sklearn.linear_model import Ridge

ridge, rmse_ridge = evaluate(
    "Ridge",
    Ridge(alpha=10),
    X_train, y_train, X_val, y_val
)

Ridge                          | Val RMSE: 0.1311 | CV RMSE: 0.1326